baseURL = 'https://huyixi.org/'
title = 'huyixi'
theme = 'white'
copyright = '© 2024 Hu Yixi'
defaultContentLanguage = "zh"

[params]
  [params.author]
    email = 'hi@huyixi.com'
    name = 'Hu Yixi'


[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 10

[[menus.main]]
name = 'Journal'
pageRef = '/journal'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[outputs]
  home = ["HTML", "RSS"]
  posts = ["HTML", "RSS"]
  journal = ["HTML", "RSS"]
