baseURL = 'https://huyixi.org/'
languageCode = "zh-CN"
languageName = "简体中文"
title = 'huyixi'
theme = 'white'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 10

[[menus.main]]
name = 'Weekly'
pageRef = '/weekly'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
