baseURL = 'https://huyixi.org/'
languageCode = 'zh-cn'
title = 'huyixi'
theme = 'white'

[[menus.main]]
name = 'posts'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'weekly'
pageRef = '/weekly'
weight = 20

[[menus.main]]
name = 'projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

