name = 'White'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

homepage = 'https://github.com/huyixi/white'

demosite = 'https://huyixi.org'

tags = ['blog', 'simple']
features = ['some', 'awesome', 'features']

[author]
  name = 'huyixi'
  homepage = 'https://huyixi.com'
